import { computeGrade } from './scoring.js'

// Seed catalog so Browse isn't empty on first load and has enough volume to
// actually exercise every filter/sort option. Photos are real, freely-
// licensed photos (mostly Wikimedia Commons, several from a Dutch municipal
// museum's clothing collection), each downloaded and visually checked for
// two hard rules: no humans in frame (mannequins/hangers/flat-lay only,
// and only headless/faceless forms, nothing photographed on a person) and
// exactly one garment per photo (never a rack or a layered outfit). A few
// items include a second genuine photo of the same object (e.g. front/back)
// to demonstrate the photo gallery. Grades are precomputed with the same
// scoring engine the live Sell flow uses, so numbers stay consistent
// across the app.
//
// BASE holds every uniquely-photographed item (29). REPOSTS reuses a base
// item's real photo(s) under a different size/price/location/seller/
// condition, the way several sellers on a real marketplace independently
// list a similar secondhand piece, to pad the catalog to 50 without
// inventing photos that don't exist. Swap any of this for real product
// photography before presenting if you have it.
const BASE = [
  {
    id: 'l1',
    title: 'Denim Jacket, Classic Blue',
    description: 'Classic mid-wash denim jacket, worn a handful of times. Slight shoulder fade only visible in direct light. Fits true to size.',
    category: 'Jackets',
    size: 'M',
    gender: 'Men',
    color: 'Blue',
    location: 'Mumbai',
    basePrice: 1800,
    seller: 'Mad Hatter',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Jean%20jacket.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'slight', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: "Doesn't fit", tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd1', label: 'Slight color fade on shoulders', severity: 'moderate', confidence: 0.81, imageIndex: 0, xPct: 40, yPct: 25 },
    ],
  },
  {
    id: 'l2',
    title: 'Cotton Shirt, Striped',
    description: 'Soft cotton striped shirt, great for everyday wear. One small mark near the sleeve, otherwise in solid shape.',
    category: 'Shirts',
    size: 'L',
    gender: 'Men',
    color: 'White',
    location: 'Delhi',
    basePrice: 900,
    seller: 'Thrift Wizard',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Arnaud%20Rousseau%20Dress%20Shirt%20with%20a%20Modern%20Spread%20Collar.jpg?width=600'],
    questionnaire: { stains: 'light', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'yes' },
    provenance: { cleaningMethod: 'Machine washed', sellReason: 'Rarely wore it', tagPhoto: null, smokeFreeHome: true, petFreeHome: false },
    defects: [
      { id: 'd2', label: 'Faint mark on sleeve', severity: 'moderate', confidence: 0.68, imageIndex: 0, xPct: 70, yPct: 55 },
    ],
  },
  {
    id: 'l3',
    title: 'Knit Cardigan, Embroidered',
    description: 'Vintage-style embroidered cardigan with a bit of character. Small loose stitch at one seam, easy fix if it bothers you.',
    category: 'Sweaters',
    size: 'S',
    gender: 'Women',
    color: 'Beige',
    location: 'Bengaluru',
    basePrice: 1400,
    seller: 'Velvet Fox',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/1940%20Trachtenstrickjacke%20anagoria.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'minor', fading: 'none', stitching: 'loose', pilling: 'light', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd3', label: 'Small seam fray', severity: 'minor', confidence: 0.72, imageIndex: 0, xPct: 30, yPct: 65 },
    ],
  },
  {
    id: 'l4',
    title: 'Summer Dress, Floral',
    description: 'Lightweight floral dress, perfect for summer. No visible defects; outgrew it before it saw much wear.',
    category: 'Dresses',
    size: 'M',
    gender: 'Women',
    color: 'Multicolor',
    location: 'Pune',
    basePrice: 1600,
    seller: 'Cloud Walker',
    photos: ["https://commons.wikimedia.org/wiki/Special:FilePath/Woman's%20Floral%20Print%20Dress%20Worn%20by%20Mabel-Ruth%20Anheuser%20-%20DPLA%20-%20cbf4e1788adbf5cd34a5debba3c28a8b%20(page%202).jpg?width=600"],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'yes' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Outgrew it', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l5',
    title: 'Chino Trousers, Beige',
    description: 'Classic beige chinos, barely worn. Comfortable fit, no stains or fading.',
    category: 'Trousers',
    size: 'XL',
    gender: 'Men',
    color: 'Beige',
    location: 'Chennai',
    basePrice: 1100,
    seller: 'Rusty Compass',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Back%20side%20Chino%20trousers%20with%20welt%20pocket.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'yes' },
    provenance: { cleaningMethod: 'Not cleaned', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: false, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l6',
    title: 'Printed One Piece, Floral Romper',
    description: 'Fun printed romper, worn for one event. Slight fading at the fold lines from storage, nothing else.',
    category: 'One Piece',
    size: 'S',
    gender: 'Women',
    color: 'Multicolor',
    location: 'Hyderabad',
    basePrice: 1300,
    seller: 'Lucky Magpie',
    photos: ["https://commons.wikimedia.org/wiki/Special:FilePath/Girl's%20Printed%20Dress%20Worn%20by%20Jessica%20Graves%20-%20DPLA%20-%20f84403bb4ddf9207401567a879dc851f%20(page%202).jpg?width=600"],
    questionnaire: { stains: 'none', tears: 'none', fading: 'slight', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd6', label: 'Mild fading at fold lines', severity: 'moderate', confidence: 0.7, imageIndex: 0, xPct: 55, yPct: 40 },
    ],
  },
  {
    id: 'l7',
    title: 'Checked Cotton Kurta, Beige',
    description: 'Handloom checked cotton kurta, comfortable everyday fit. A couple of crease lines from folded storage, otherwise clean.',
    category: 'Shirts',
    size: 'L',
    gender: 'Men',
    color: 'Beige',
    location: 'Delhi',
    basePrice: 950,
    seller: 'Sly Otter',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Handloom%20Cotton%20Kurta%20in%20Tea%20Dyed.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd7', label: 'Fold crease lines from storage', severity: 'minor', confidence: 0.62, imageIndex: 0, xPct: 45, yPct: 45 },
    ],
  },
  {
    id: 'l8',
    title: 'Cable-Knit Cardigan, Cream',
    description: 'Chunky cream cable-knit cardigan, warm and roomy. A small snag near one cuff, disclosed below, everything else holding up well.',
    category: 'Sweaters',
    size: 'M',
    gender: 'Women',
    color: 'White',
    location: 'Bengaluru',
    basePrice: 1200,
    seller: 'Paper Moon',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Aran%20cardigan.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'minor', fading: 'none', stitching: 'none', pilling: 'light', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: false },
    defects: [
      { id: 'd8', label: 'Small snag near cuff', severity: 'minor', confidence: 0.65, imageIndex: 0, xPct: 20, yPct: 60 },
    ],
  },
  {
    id: 'l9',
    title: 'Formal Waistcoat, Maroon',
    description: 'Maroon formal waistcoat, four pockets, wore it to a handful of events. Fabric has a slight sheen from wear in the light, nothing else notable.',
    category: 'Jackets',
    size: 'M',
    gender: 'Men',
    color: 'Red',
    location: 'Delhi',
    basePrice: 1000,
    seller: 'Quiet Storm',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Waistcoat.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'slight', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: "Doesn't fit", tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd9', label: 'Slight sheen/wear on fabric', severity: 'minor', confidence: 0.58, imageIndex: 0, xPct: 50, yPct: 50 },
    ],
  },
  {
    id: 'l10',
    title: 'Cotton Twill Trousers, White',
    description: 'Crisp white cotton twill trousers, straight cut. A touch of yellowing along the fold from storage, otherwise like new.',
    category: 'Trousers',
    size: 'L',
    gender: 'Men',
    color: 'White',
    location: 'Mumbai',
    basePrice: 1050,
    seller: 'Neon Raven',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Broek%20van%20wit%20keperkatoen,%20objectnr%2072797.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'slight', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd10', label: 'Slight yellowing along fold', severity: 'minor', confidence: 0.55, imageIndex: 0, xPct: 50, yPct: 60 },
    ],
  },
  {
    id: 'l11',
    title: 'Track Pants, Black',
    description: 'Everyday black track pants with drawstring waist. Light pilling on the inner thigh from wear, nothing else.',
    category: 'Trousers',
    size: 'M',
    gender: 'Men',
    color: 'Black',
    location: 'Delhi',
    basePrice: 850,
    seller: 'Mad Hatter',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Zwarte%20broek%20van%20trainingspak%20%E2%80%9CAustralian%E2%80%9D,%20objectnr%2027233-2.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'light', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Machine washed', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: false },
    defects: [
      { id: 'd11', label: 'Light pilling on inner thigh', severity: 'minor', confidence: 0.6, imageIndex: 0, xPct: 40, yPct: 70 },
    ],
  },
  {
    id: 'l12',
    title: 'Cotton Shorts, White',
    description: 'Tailored white cotton shorts, pleated front. Barely worn, no visible wear.',
    category: 'Trousers',
    size: 'M',
    gender: 'Men',
    color: 'White',
    location: 'Chennai',
    basePrice: 650,
    seller: 'Thrift Wizard',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Korte%20broek%20van%20wit%20keperkatoen,%20objectnr%2072796.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'yes' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: "Doesn't fit", tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l13',
    title: 'Draped Wrap Jacket, Navy',
    description: 'Statement navy wrap jacket with dramatic sleeves and a single button closure. Worn a few times, holding up well.',
    category: 'Jackets',
    size: 'M',
    gender: 'Women',
    color: 'Blue',
    location: 'Bengaluru',
    basePrice: 1900,
    seller: 'Velvet Fox',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Blauwe%20jas,%20objectnr%2069153.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l14',
    title: 'Wool Peacoat, Black',
    description: 'Classic double-breasted black wool peacoat. Light pilling at the cuffs from regular wear, everything else in solid shape.',
    category: 'Jackets',
    size: 'S',
    gender: 'Women',
    color: 'Black',
    location: 'Pune',
    basePrice: 2400,
    seller: 'Cloud Walker',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Zwarte%20wollen%20jas,%20objectnr%2087608.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'light', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Outgrew it', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd14', label: 'Light pilling at cuffs', severity: 'minor', confidence: 0.6, imageIndex: 0, xPct: 25, yPct: 75 },
    ],
  },
  {
    id: 'l15',
    title: 'Trench Coat, White',
    description: 'Long white trench coat with a tie belt. One faint mark near the pocket, fully disclosed, otherwise clean.',
    category: 'Jackets',
    size: 'M',
    gender: 'Women',
    color: 'White',
    location: 'Hyderabad',
    basePrice: 2100,
    seller: 'Rusty Compass',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Jas,%20objectnr%20286.3.jpg?width=600'],
    questionnaire: { stains: 'light', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: false },
    defects: [
      { id: 'd15', label: 'Faint mark near pocket', severity: 'moderate', confidence: 0.64, imageIndex: 0, xPct: 30, yPct: 55 },
    ],
  },
  {
    id: 'l16',
    title: 'Embroidered Vest, Turquoise',
    description: 'Long embroidered vest, turquoise with gold floral embroidery throughout. Statement piece, worn only a couple of times.',
    category: 'Jackets',
    size: 'M',
    gender: 'Women',
    color: 'Multicolor',
    location: 'Mumbai',
    basePrice: 1300,
    seller: 'Lucky Magpie',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Turquoise%20gilet%20met%20goudbruin%20borduursel,%20objectnr%2068326-1-2(2).JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Not cleaned', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l17',
    title: 'Striped Crewneck Sweater, Grey',
    description: 'Black and grey striped crewneck sweater, soft knit. Light pilling on the sleeves from wear.',
    category: 'Sweaters',
    size: 'L',
    gender: 'Men',
    color: 'Grey',
    location: 'Delhi',
    basePrice: 1150,
    seller: 'Sly Otter',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Trui,%20horizontaal%20zwartgrijs%20gestreept,%20merk%20Springfield,%20maat%20M,%20objectnr%2086526.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'light', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Machine washed', sellReason: "Doesn't fit", tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd17', label: 'Light pilling on sleeves', severity: 'minor', confidence: 0.58, imageIndex: 0, xPct: 25, yPct: 40 },
    ],
  },
  {
    id: 'l18',
    title: 'Draped Tunic Sweater, Navy',
    description: 'Oversized navy tunic sweater with a cowl-style draped neckline. Soft knit, no notable wear.',
    category: 'Sweaters',
    size: 'M',
    gender: 'Women',
    color: 'Blue',
    location: 'Bengaluru',
    basePrice: 1400,
    seller: 'Paper Moon',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Donkerblauwe%20tuniek%20of%20trui%20met%20brede%20hals,%20%E2%80%9CComme%20des%20garcons%E2%80%9D,%20objectnr%2087593.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: false },
    defects: [],
  },
  {
    id: 'l19',
    title: 'Tie-Waist Dress, Navy',
    description: 'Sleeveless navy dress with a tie waist. Simple, versatile cut. Clean condition throughout.',
    category: 'Dresses',
    size: 'M',
    gender: 'Women',
    color: 'Blue',
    location: 'Pune',
    basePrice: 1700,
    seller: 'Quiet Storm',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Paarse%20jurk,%20objectnr%2027756.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l20',
    title: 'Colourblock Midi Dress, Yellow-Green',
    description: 'Retro-style colourblock midi dress, yellow bodice and green skirt. Slight fading on the skirt panel, disclosed below.',
    category: 'Dresses',
    size: 'S',
    gender: 'Women',
    color: 'Multicolor',
    location: 'Chennai',
    basePrice: 1500,
    seller: 'Neon Raven',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Geel%20met%20groen%20jumpsuit,%20objectnr%2069138.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'slight', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd20', label: 'Slight fading on skirt panel', severity: 'minor', confidence: 0.56, imageIndex: 0, xPct: 50, yPct: 65 },
    ],
  },
  {
    id: 'l21',
    title: 'Pleated Occasion Dress, Red',
    description: 'Dramatic red pleated dress with a ruffled high neckline, great for occasions. Worn once, excellent condition.',
    category: 'Dresses',
    size: 'M',
    gender: 'Women',
    color: 'Red',
    location: 'Hyderabad',
    basePrice: 2200,
    seller: 'Mad Hatter',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Blouse,%20objectnr%20705.2.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l22',
    title: 'Check Shirt, Blue',
    description: 'Blue and white check cotton shirt, button-down collar. Clean, ready to wear.',
    category: 'Shirts',
    size: 'L',
    gender: 'Men',
    color: 'Blue',
    location: 'Mumbai',
    basePrice: 950,
    seller: 'Thrift Wizard',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Ruitjeshemd,%20objectnr%20KA%2020496.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Machine washed', sellReason: 'Rarely wore it', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l23',
    title: 'Button-Down Shirt, Pink',
    description: 'Bright pink button-down shirt with a pointed collar. Light wrinkling from storage, otherwise clean.',
    category: 'Shirts',
    size: 'S',
    gender: 'Women',
    color: 'Red',
    location: 'Delhi',
    basePrice: 850,
    seller: 'Velvet Fox',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Damesoverhemd,%20objectnr%20KA%2019679.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l24',
    title: 'Linen Shirt, White',
    description: 'Airy white linen shirt with a stand collar. Minor loose stitching at one cuff, disclosed below.',
    category: 'Shirts',
    size: 'M',
    gender: 'Men',
    color: 'White',
    location: 'Bengaluru',
    basePrice: 1000,
    seller: 'Cloud Walker',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Wit%20linnen%20herenoverhemd,%20objectnr%2072966.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'loose', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd24', label: 'Minor loose stitching at cuff', severity: 'minor', confidence: 0.57, imageIndex: 0, xPct: 20, yPct: 80 },
    ],
  },
  {
    id: 'l25',
    title: 'Embroidered Blouse, White',
    description: 'White cotton blouse with red embroidered trim at the neckline and sleeves. One light stain near the hem, fully disclosed.',
    category: 'Shirts',
    size: 'S',
    gender: 'Women',
    color: 'White',
    location: 'Pune',
    basePrice: 900,
    seller: 'Rusty Compass',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Blouse,%20objectnr%20KA%2019674.jpg?width=600'],
    questionnaire: { stains: 'light', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: 'Outgrew it', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd25', label: 'Light stain near hem', severity: 'moderate', confidence: 0.63, imageIndex: 0, xPct: 45, yPct: 85 },
    ],
  },
  {
    id: 'l26',
    title: 'Sheer Blouse, Red',
    description: 'Red sheer-overlay blouse with gold print detail. Delicate fabric, handled with care, worn a few times.',
    category: 'Shirts',
    size: 'S',
    gender: 'Women',
    color: 'Red',
    location: 'Chennai',
    basePrice: 950,
    seller: 'Lucky Magpie',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Blouse,%20objectnr%20812.1.jpg?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l27',
    title: 'Long-Sleeve Jumpsuit, Turquoise',
    description: 'Turquoise long-sleeve jumpsuit with a draped neckline. Comfortable jersey fabric, no notable wear.',
    category: 'One Piece',
    size: 'M',
    gender: 'Women',
    color: 'Blue',
    location: 'Hyderabad',
    basePrice: 1600,
    seller: 'Sly Otter',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Turquoise%20jumpsuit,%20objectnr%2069128.JPG?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Dry cleaned', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l28',
    title: 'Silk Pyjama Set, Peach',
    description: 'Two-piece peach silk pyjama set with tonal embroidery, sleeveless top and wide-leg pants. Elegant loungewear, gently used.',
    category: 'Pyjamas',
    size: 'M',
    gender: 'Women',
    color: 'Beige',
    location: 'Mumbai',
    basePrice: 1200,
    seller: 'Paper Moon',
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Tweedelige%20pyjama,%20objectnr%20138.12.tif?width=600'],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Hand washed', sellReason: 'Other', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l29',
    title: 'Printed Pyjama Onesie, Cream',
    description: 'Cream cotton pyjama onesie with a playful balloon print, button front, matching collar. Front and back shown. Soft and well cared for.',
    category: 'Pyjamas',
    size: 'XS',
    gender: 'Women',
    color: 'Multicolor',
    location: 'Delhi',
    basePrice: 700,
    seller: 'Quiet Storm',
    photos: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Hansop%20of%20kinderpyjama%20van%20wit%20katoen%20met%20ballonnen,%20objectnr%2069192(1).JPG?width=600',
      'https://commons.wikimedia.org/wiki/Special:FilePath/Hansop%20of%20kinderpyjama%20van%20wit%20katoen%20met%20ballonnen,%20objectnr%2069192(2).JPG?width=600',
    ],
    questionnaire: { stains: 'none', tears: 'none', fading: 'none', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Machine washed', sellReason: 'Outgrew it', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [],
  },
  {
    id: 'l51',
    title: 'Belted Trench Coat, Cream',
    description: 'Long cream belted trench coat, structured shoulders, patch pockets. Front and back shown. Some light age-related discoloration on the fabric, disclosed below.',
    category: 'Jackets',
    size: 'L',
    gender: 'Women',
    color: 'Beige',
    location: 'Bengaluru',
    basePrice: 2300,
    seller: 'Cloud Walker',
    photos: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Lange%20ecrukleurige%20dames%20paardrij-jas,%20objectnr%2069544-1-3(1).JPG?width=600',
      'https://commons.wikimedia.org/wiki/Special:FilePath/Lange%20ecrukleurige%20dames%20paardrij-jas,%20objectnr%2069544-1-3(2).JPG?width=600',
    ],
    questionnaire: { stains: 'light', tears: 'none', fading: 'slight', stitching: 'none', pilling: 'none', tagsAttached: 'no' },
    provenance: { cleaningMethod: 'Not cleaned', sellReason: 'Decluttering', tagPhoto: null, smokeFreeHome: true, petFreeHome: true },
    defects: [
      { id: 'd51', label: 'Light age-related discoloration', severity: 'moderate', confidence: 0.6, imageIndex: 0, xPct: 40, yPct: 60 },
    ],
  },
]

// Each entry reposts a BASE item's real photo(s) under different
// size/price/location/seller/condition, so Browse has 50 listings total
// without fabricating photos that don't exist.
const REPOSTS = [
  { id: 'l30', baseId: 'l1', size: 'L', location: 'Chennai', seller: 'Neon Raven', basePrice: 1700, questionnaire: { tears: 'minor' } },
  { id: 'l31', baseId: 'l2', size: 'M', location: 'Hyderabad', seller: 'Quiet Storm', basePrice: 950, questionnaire: { fading: 'slight' } },
  { id: 'l32', baseId: 'l3', size: 'M', location: 'Mumbai', seller: 'Lucky Magpie', basePrice: 1450, questionnaire: { tears: 'none', stitching: 'none', pilling: 'none' }, defects: [] },
  { id: 'l33', baseId: 'l4', size: 'S', location: 'Delhi', seller: 'Mad Hatter', basePrice: 1650 },
  { id: 'l34', baseId: 'l5', size: 'L', location: 'Bengaluru', seller: 'Thrift Wizard', basePrice: 1150, questionnaire: { pilling: 'light' }, defects: [{ id: 'd34', label: 'Light pilling at thighs', severity: 'minor', confidence: 0.5, imageIndex: 0, xPct: 50, yPct: 40 }] },
  { id: 'l35', baseId: 'l6', size: 'M', location: 'Pune', seller: 'Velvet Fox', basePrice: 1350 },
  { id: 'l36', baseId: 'l10', size: 'M', location: 'Chennai', seller: 'Cloud Walker', basePrice: 1000, questionnaire: { fading: 'none' }, defects: [] },
  { id: 'l37', baseId: 'l11', size: 'L', location: 'Hyderabad', seller: 'Rusty Compass', basePrice: 900, questionnaire: { pilling: 'heavy' }, defects: [{ id: 'd37', label: 'Heavy pilling on inner thigh', severity: 'moderate', confidence: 0.7, imageIndex: 0, xPct: 40, yPct: 70 }] },
  { id: 'l38', baseId: 'l13', size: 'S', location: 'Mumbai', seller: 'Sly Otter', basePrice: 1950 },
  { id: 'l39', baseId: 'l14', size: 'M', location: 'Delhi', seller: 'Paper Moon', basePrice: 2350 },
  { id: 'l40', baseId: 'l17', size: 'M', location: 'Bengaluru', seller: 'Quiet Storm', basePrice: 1200 },
  { id: 'l41', baseId: 'l18', size: 'L', location: 'Pune', seller: 'Lucky Magpie', basePrice: 1350 },
  { id: 'l42', baseId: 'l19', size: 'S', location: 'Chennai', seller: 'Mad Hatter', basePrice: 1750 },
  { id: 'l43', baseId: 'l21', size: 'L', location: 'Hyderabad', seller: 'Neon Raven', basePrice: 2150 },
  { id: 'l44', baseId: 'l22', size: 'M', location: 'Mumbai', seller: 'Thrift Wizard', basePrice: 900 },
  { id: 'l45', baseId: 'l24', size: 'L', location: 'Delhi', seller: 'Cloud Walker', basePrice: 1050, questionnaire: { stitching: 'none' }, defects: [] },
  { id: 'l46', baseId: 'l25', size: 'M', location: 'Bengaluru', seller: 'Rusty Compass', basePrice: 950 },
  { id: 'l47', baseId: 'l27', size: 'S', location: 'Pune', seller: 'Sly Otter', basePrice: 1550 },
  { id: 'l48', baseId: 'l7', size: 'M', location: 'Chennai', seller: 'Paper Moon', basePrice: 1000 },
  { id: 'l49', baseId: 'l8', size: 'L', location: 'Hyderabad', seller: 'Velvet Fox', basePrice: 1250 },
  { id: 'l50', baseId: 'l9', size: 'L', location: 'Mumbai', seller: 'Quiet Storm', basePrice: 1050 },
]

const byId = Object.fromEntries(BASE.map((b) => [b.id, b]))

const RAW = [
  ...BASE,
  ...REPOSTS.map(({ id, baseId, questionnaire, defects, ...overrides }) => {
    const base = byId[baseId]
    return {
      ...base,
      ...overrides,
      id,
      questionnaire: { ...base.questionnaire, ...questionnaire },
      defects: defects ?? base.defects,
    }
  }),
]

export const SEED_LISTINGS = RAW.map((l, i) => {
  const grade = computeGrade({ basePrice: l.basePrice, questionnaire: l.questionnaire, provenance: l.provenance, defects: l.defects })
  return {
    ...l,
    grade: { ...grade, defects: l.defects, source: 'simulated', fellBack: false, fallbackReason: null },
    status: 'listed',
    // Staggered so "New Arrivals" has a real order instead of ties.
    createdAt: Date.now() - (RAW.length - i) * 3600_000,
  }
})
